version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      ME_CONFIG_MONGODB_PORT: '27017'
    links:
      - mongodb
    ports:
      - "8081:8081"
